//
//  ShowRoomInteractor.swift
//  LuckyPocket
//
//  Created by Desen Guo on 2018-10-28.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowRoomBusinessLogic
{
//  func doSomething(request: ShowRoom.Something.Request)
}

protocol ShowRoomDataStore
{
  //var name: String { get set }
}

class ShowRoomInteractor: ShowRoomBusinessLogic, ShowRoomDataStore
{
//  var presenter: ShowRoomPresentationLogic?
////  var worker: ShowRoomWorker?
//  //var name: String = ""
//  
//  // MARK: Do something
//  
//  func doSomething(request: ShowRoom.Something.Request)
//  {
//    worker = ShowRoomWorker()
//    worker?.doSomeWork()
//    
//    let response = ShowRoom.Something.Response()
////    presenter?.presentSomething(response: response)
//  }
}
