//
//  ListRoomsRouter.swift
//  LuckyPocket
//
//  Created by Desen Guo on 2018-10-27.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRoomsRoutingLogic
{
  func routeToShowRoom(segue: UIStoryboardSegue?)
    func routeToCreateRoom(segue: UIStoryboardSegue?)
}

protocol ListRoomsDataPassing
{
  var dataStore: ListRoomsDataStore? { get }
}

class ListRoomsRouter: NSObject, ListRoomsRoutingLogic, ListRoomsDataPassing
{
  weak var viewController: ListRoomsViewController?
  var dataStore: ListRoomsDataStore?
  
  // MARK: Routing
  
  func routeToShowRoom(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ShowRoomViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToShowRoom(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! ShowRoomViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToShowRoom(source: dataStore!, destination: &destinationDS)
      navigateToShowRoom(source: viewController!, destination: destinationVC)
    }
  }
    
    func routeToCreateRoom(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! CreateRoomViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateRoom(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! CreateRoomViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateRoom(source: dataStore!, destination: &destinationDS)
            navigateToCreateRoom(source: viewController!, destination: destinationVC)
        }
    }

  // MARK: Navigation
  
  func navigateToShowRoom(source: ListRoomsViewController, destination: ShowRoomViewController)
  {
    source.show(destination, sender: nil)
  }
    
    func navigateToCreateRoom(source: ListRoomsViewController, destination: CreateRoomViewController)
    {
        source.show(destination, sender: nil)
    }
  
  // MARK: Passing data
  
  func passDataToShowRoom(source: ListRoomsDataStore, destination: inout ShowRoomDataStore)
  {
//    destination.name = source.name
  }
    
    func passDataToCreateRoom(source: ListRoomsDataStore, destination: inout CreateRoomDataStore)
    {
//        destination.name = source.name
    }
}
