//
//  ListRoomsPresenter.swift
//  LuckyPocket
//
//  Created by Desen Guo on 2018-10-27.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRoomsPresentationLogic
{
  func presentFetchedRooms(response: ListRooms.FetchRooms.Response)
}

class ListRoomsPresenter: ListRoomsPresentationLogic
{
  weak var viewController: ListRoomsDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedRooms(response: ListRooms.FetchRooms.Response)
  {
    var displayedRooms:[ListRooms.FetchRooms.ViewModel.DisplayedRoom] = []
    for room in response.rooms{
        let displayedRoom = ListRooms.FetchRooms.ViewModel.DisplayedRoom(id: "", name: "")
        //todo room -> displayedRoom
        displayedRooms.append(displayedRoom)
    }
    let viewModel = ListRooms.FetchRooms.ViewModel(displayedRooms: displayedRooms)
    viewController?.displayFetchedRooms(viewModel: viewModel)
  }
}
