//
//  ListRoomsModels.swift
//  LuckyPocket
//
//  Created by Desen Guo on 2018-10-27.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListRooms
{
  // MARK: Use cases
  
  enum FetchRooms
  {
    struct Request
    {
    }
    struct Response
    {
        var rooms: [Room]
    }
    struct ViewModel
    {
        struct DisplayedRoom
        {
            var id: String
            var name: String
        }
        var displayedRooms: [DisplayedRoom]
    }
  }
}
