//
//  WelcomeRouter.swift
//  LuckyPocket
//
//  Created by desen guo on 2018-10-24.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic
{
    func routeToLogin()
    func routeToSignup()
}

protocol WelcomeDataPassing
{

}

class WelcomeRouter: NSObject, WelcomeRoutingLogic
{
  weak var viewController: WelcomeViewController?
  
  // MARK: Routing
  
    func routeToLogin()
    {
        viewController!.performSegue(withIdentifier: "Login", sender: nil)
    }
    func routeToSignup()
    {
                viewController!.performSegue(withIdentifier: "Signup", sender: nil)
    }
}
