//
//  SignupRouter.swift
//  LuckyPocket
//
//  Created by desen guo on 2018-10-24.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignupRoutingLogic
{
  func routeToHome()
    func routeBack()
}

class SignupRouter: NSObject, SignupRoutingLogic
{
  weak var viewController: SignupViewController?
  
  // MARK: Routing
  
    func routeToHome()
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainNavigator") as! UINavigationController
        viewController!.show(destinationVC, sender: nil)
    }
    
    func routeBack()
    {
        viewController!.dismiss(animated: true, completion: nil)
    }
}
