//
//  SignupModels.swift
//  LuckyPocket
//
//  Created by desen guo on 2018-10-24.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Signup {
    // MARK: Use cases
    struct Request {
        var name: String
        var email: String
        var password: String
    }
    
    struct Response {
        var user: User?
        
        init(data: [String:Any]) {
            self.user = User(
                id: data["id"] as! Int,
                name: data["name"] as! String,
                email: data["email"] as! String,
                chatkit_id: data["chatkit_id"] as! String
            )
        }
    }
}
