//
//  SignupViewController.swift
//  LuckyPocket
//
//  Created by desen guo on 2018-10-24.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK display
protocol SignupFormErrorLogic {
    func showValidationError(_ message: String)
}

class SignupViewController: UIViewController, SignupFormErrorLogic
{
  var interactor: SignupBusinessLogic?
  var router: (NSObjectProtocol & SignupRoutingLogic)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignupInteractor()
    let router = SignupRouter()
    viewController.interactor = interactor
    viewController.router = router
    router.viewController = viewController
  }
  
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
  }
  
  // MARK: Input fields
   
    // MARK: Actions
    @IBAction func signupButtonPressed(_ sender:Any)
    {
        let request = Signup.Request(name: "", email: "", password: "")
        interactor?.createAccount(request: request)
    }
    
    @IBAction func cancelButtonPressed(_ sender: Any)
    {
        router?.routeBack()
    }
    
    // MARK display
    func showValidationError(_ message: String) {
        let alertCtrl = UIAlertController(title: "Oops! An error occurred", message: message, preferredStyle: .alert)
        alertCtrl.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: nil))
        self.show(alertCtrl, sender: self)
    }
}
