//
//  CreateRoomInteractor.swift
//  LuckyPocket
//
//  Created by Desen Guo on 2018-10-28.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRoomBusinessLogic
{
//  func doSomething(request: CreateRoom.Something.Request)
}

protocol CreateRoomDataStore
{
  //var name: String { get set }
}

class CreateRoomInteractor: CreateRoomBusinessLogic, CreateRoomDataStore
{
//  var presenter: CreateRoomPresentationLogic?
//  var worker: CreateRoomWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: CreateRoom.Something.Request)
//  {
////    worker = CreateRoomWorker()
////    worker?.doSomeWork()
////    
////    let response = CreateRoom.Something.Response()
////    presenter?.presentSomething(response: response)
//  }
}
