//
//  LoginViewController.swift
//  LuckyPocket
//
//  Created by desen guo on 2018-10-24.
//  Copyright (c) 2018 desen guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//Mark Display
protocol LoginFormErrorLogic: class {
    func showValidationError(_ message: String)
}

class LoginViewController: UIViewController, LoginFormErrorLogic {
    
    // MARK: Properties
    
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic)?
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let router = LoginRouter()
        let interactor = LoginInteractor()
        
        viewController.interactor = interactor
        viewController.router = router
        interactor.router = router
        interactor.viewController = viewController
        router.viewController = viewController
}

// MARK: Input fields

    //MARK: Action
    @IBAction func loginButtonPressed(_ sender: Any) {
        interactor?.login()
    }
    
    @IBAction func cancelButtonPressed(_ sender: Any)
    {
        router?.routeBack()
    }
    
    //MARK Display
    func showValidationError(_ message: String) -> Void {
        let alert = UIAlertController(title: "Error logging in", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Ok", style: .cancel, handler: nil))
        self.show(alert, sender: self)
    }
}
